export interface GameOptions {
    majorRadius: number;
    minorRadius: number;
    trackWidth: number;
    samples: number;
    straightLength: number;
    cornerRadiusInner: number;
    cornerRadiusOuter: number;
    bankAngleStraights: number;
    bankAngleCorners: number;
    wheelBase: number;
    mass: number;
    cgToFront: number;
    cgToRear: number;
    maxSteer: number;
    engineForce: number;
    brakeForce: number;
    dragCoeff: number;
    frontalArea: number;
    airDensity: number;
    rollingResistance: number;
    baseFrontGrip: number;
    baseRearGrip: number;
    yawInertia: number;
    lateralDamping: number;
    enableWalls: boolean;
    cameraDistance: number;
    cameraHeight: number;
    shadowQuality: number;
    enableClouds: boolean;
    bodyColor: number;
    asphaltRepeatU: number;
    asphaltRepeatV: number;
    grassRepeatU: number;
    grassRepeatV: number;
}
export declare const defaultOptions: GameOptions;
export declare function mountGame(container: HTMLElement, options?: Partial<GameOptions>): void;
export declare function unmountGame(): void;
